definitions:
  app.Pager:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_rows:
        type: integer
    type: object
  model.Articles:
    properties:
      content:
        type: string
      cover_image_url:
        type: string
      created_on:
        description: |-
          CreatedBy  string `json:"created_by"`
          ModifiedBy string `json:"modified_by"`
        type: string
      deleted_on:
        type: string
      desc:
        type: string
      id:
        type: integer
      is_del:
        type: string
      is_draft:
        type: integer
      modified_on:
        type: string
      state:
        type: integer
      title:
        type: string
    type: object
  model.ArticlesSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Articles'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
    type: object
  model.Diarys:
    properties:
      content:
        type: string
      created_on:
        description: |-
          CreatedBy  string `json:"created_by"`
          ModifiedBy string `json:"modified_by"`
        type: string
      deleted_on:
        type: string
      id:
        type: integer
      is_del:
        type: string
      modified_on:
        type: string
      title:
        type: string
    type: object
  model.DiarysSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Diarys'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
    type: object
  model.Likes:
    properties:
      created_on:
        description: |-
          CreatedBy  string `json:"created_by"`
          ModifiedBy string `json:"modified_by"`
        type: string
      deleted_on:
        type: string
      id:
        type: integer
      is_del:
        type: string
      modified_on:
        type: string
      post_id:
        type: integer
      type:
        $ref: '#/definitions/model.Type'
      user_id:
        type: integer
    type: object
  model.LikesSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Likes'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
    type: object
  model.Tags:
    properties:
      created_on:
        description: |-
          CreatedBy  string `json:"created_by"`
          ModifiedBy string `json:"modified_by"`
        type: string
      deleted_on:
        type: string
      id:
        type: integer
      is_del:
        type: string
      modified_on:
        type: string
      name:
        type: string
      state:
        type: integer
    type: object
  model.TagsSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tags'
        type: array
    type: object
  model.Type:
    enum:
    - blog
    - comment
    type: string
    x-enum-varnames:
    - Blog
    - Comment
  model.Users:
    properties:
      avater:
        type: string
      created_on:
        description: |-
          CreatedBy  string `json:"created_by"`
          ModifiedBy string `json:"modified_by"`
        type: string
      deleted_on:
        type: string
      email:
        type: string
      id:
        type: integer
      introduce:
        type: string
      is_del:
        type: string
      modified_on:
        type: string
      password:
        type: string
      state:
        type: integer
      username:
        type: string
    type: object
  model.UsersSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Users'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
    type: object
info:
  contact: {}
  description: 博客系统
  title: 博客系统
  version: "1.0"
paths:
  /api/v1/articles:
    get:
      parameters:
      - description: 文章名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.ArticlesSwagger'
      summary: 获取文章列表
    post:
      parameters:
      - description: 文章名称
        in: query
        maxLength: 100
        minLength: 3
        name: name
        required: true
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 创建者
        in: body
        maxLength: 100
        minLength: 3
        name: created_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Articles'
      summary: 新增文章
  /api/v1/articles/{id}:
    delete:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Articles'
      summary: 删除文章
    get:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Articles'
      summary: 获取单个文章
    put:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: path
        name: state
        type: integer
      - description: 文章名称
        in: query
        maxLength: 100
        minLength: 3
        name: name
        type: string
      - description: 修改者
        in: body
        maxLength: 100
        minLength: 3
        name: created_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Articles'
      summary: 更新文章
  /api/v1/diarys:
    get:
      parameters:
      - description: 说说名称
        in: query
        maxLength: 100
        name: name
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.DiarysSwagger'
      summary: 获取说说列表
    post:
      parameters:
      - description: 说说名称
        in: query
        maxLength: 100
        minLength: 3
        name: name
        required: true
        type: string
      - description: 内容
        in: body
        maxLength: 1000
        minLength: 3
        name: content
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Diarys'
      summary: 新增说说
  /api/v1/diarys/{id}:
    delete:
      parameters:
      - description: 说说ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Diarys'
      summary: 删除说说
    get:
      parameters:
      - description: 说说ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Diarys'
      summary: 获取单个说说详情
    put:
      parameters:
      - description: 说说ID
        in: path
        name: id
        required: true
        type: integer
      - description: 说说名称
        in: query
        maxLength: 100
        minLength: 3
        name: name
        required: true
        type: string
      - description: 内容
        in: body
        maxLength: 1000
        minLength: 3
        name: content
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Diarys'
      summary: 更新说说
  /api/v1/likes:
    get:
      parameters:
      - description: 博客或说说ID
        in: path
        name: postId
        required: true
        type: integer
      - default: blog
        description: Enums(blog, common) default(blog)
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.LikesSwagger'
      summary: 通过博客或说说ID获取点赞列表
  /api/v1/likes/{id}:
    post:
      parameters:
      - description: 说说ID
        in: path
        name: id
        required: true
        type: integer
      - description: 类型 blog是图文 comment是评论
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Likes'
      summary: 点赞
  /api/v1/tags:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagsSwagger'
      summary: 获取所有标签
    post:
      parameters:
      - description: 标签名称
        in: query
        maxLength: 100
        minLength: 3
        name: name
        required: true
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 创建者
        in: body
        maxLength: 100
        minLength: 3
        name: created_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Tags'
      summary: 新增标签
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Tags'
      summary: 删除标签
    put:
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      - description: 标签名称
        in: query
        maxLength: 100
        minLength: 3
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 修改者
        in: body
        maxLength: 100
        minLength: 3
        name: created_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Tags'
      summary: 更新标签
  /api/v1/users:
    get:
      parameters:
      - description: 用户名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.UsersSwagger'
      summary: 获取用户列表
    post:
      parameters:
      - description: 用户名称
        in: body
        maxLength: 100
        minLength: 1
        name: name
        required: true
        schema:
          type: string
      - description: 头像文件
        in: formData
        name: avater
        required: true
        type: file
      - default: 1
        description: 状态
        in: body
        name: state
        schema:
          enum:
          - 0
          - 1
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Users'
      summary: 新增用户
  /api/v1/users/{id}:
    delete:
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Users'
      summary: 删除标签
    put:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 用户名称
        in: body
        maxLength: 100
        minLength: 1
        name: name
        required: true
        schema:
          type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 头像文件
        in: formData
        name: avater
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Users'
      summary: 更新用户信息
swagger: "2.0"
